## GENERATED BY DEEPSEEK V4
class_name GSInterface
extends RefCounted
## GDScript 接口支持基类（Java 风格接口的纯 GDScript 实现）。
##
## 接口脚本继承本类后：
## 1. 契约方法 = 接口脚本中声明的桩方法（桩体通过 _forward() 转发到目标对象）；
## 2. 契约检查 = GSInterface.implements() / GSInterface.is_a()（鸭子类型）；
## 3. 静态 of(obj) 返回「视图包装壳」——真正的接口实例，
##    静态类型风格下调用接口方法/属性零警告，运行时转发到原对象。
##
## 注意：原生 is 运算符无法覆盖（引擎级限制，GDScript 不允许重载），
## 判断接口请使用自定义方法：
##     IHealth.is_implemented_by(obj)
##     GSInterface.is_a(obj, IHealth)          # 类名/接口名统一入口
## 视图本身是真正的接口实例，因此 GSInterface.is_a(IHealth.of(obj), IHealth)
## 与 IHealth.of(obj) is IHealth 均成立。

## 视图包装壳持有的具体实现对象（_ 前缀不参与契约检查）
var _target: Object = null


## ============ 实例辅助（接口桩体的转发目标） ============

## 方法转发：接口桩方法体调用本函数，把调用转发到 _target 的同名方法
func _forward(method: StringName, args: Array = []) -> Variant:
	if _target == null:
		push_error("GSInterface: 视图未绑定目标对象（接口脚本请勿直接实例化使用）")
		return null
	if not _target.has_method(method):
		push_error("GSInterface: 接口契约违反 —— 目标对象 %s 未实现方法 %s" % [_target.get_class(), method])
		return null
	return _target.callv(method, args)


## 属性读转发：接口契约属性的 getter 体
func _pget(prop: StringName) -> Variant:
	if _target == null:
		push_error("GSInterface: 视图未绑定目标对象（接口脚本请勿直接实例化使用）")
		return null
	return _target.get(prop)


## 属性写转发：接口契约属性的 setter 体
func _pset(prop: StringName, value: Variant) -> void:
	if _target == null:
		push_error("GSInterface: 视图未绑定目标对象（接口脚本请勿直接实例化使用）")
		return
	_target.set(prop, value)


## ============ 静态 API ============

## 创建视图包装壳（供各接口的静态 of() 调用）：
## 返回真正的接口实例，静态类型调用零警告，运行时转发到 obj
static func make_view(iface: Script, obj: Object) -> Variant:
	var v: Variant = iface.new()
	if v == null or not (v is Object):
		push_error("GSInterface: 无法实例化接口脚本 %s" % iface.resource_path)
		return null
	v.set("_target", obj)
	return v


## 鸭子契约检查：obj 是否实现了 iface 脚本声明的全部实例方法与属性（含父接口）。
## 若 obj 是视图包装壳，自动解包检查其真实目标对象。
static func implements(obj: Object, iface: Script) -> bool:
	obj = _unwrap(obj)
	if obj == null or iface == null:
		return false
	for m in collect_methods(iface):
		if not obj.has_method(m):
			return false
	for p in collect_properties(iface):
		if not (String(p) in obj):
			return false
	return true


## 统一类型判断入口。type 可为：
##   - 脚本类/接口引用：直接把 class_name 作为值传入（如 IHealth、Monster）
##   - 原生类名：String/StringName（如 "Node2D"）
##   - 全局脚本类名字符串：依赖引擎运行时暴露全局类列表，尽力而为
## 语义：名义类型（脚本继承链）优先；接口按结构化契约判断。
static func is_a(obj: Object, type: Variant) -> bool:
	obj = _unwrap(obj)
	if obj == null:
		return false
	if type is Script:
		if _is_subclass_of_script(obj, type):
			return true
		return implements(obj, type)
	if type is StringName or type is String:
		var cn := StringName(type)
		if ClassDB.class_exists(cn):
			return ClassDB.is_parent_class(obj.get_class(), cn)
		var path := find_global_class_path(cn)
		if path != "":
			var s: Script = load(path)
			if s != null:
				return is_a(obj, s)
	return false


## 动态调用辅助：不创建视图时的轻量调用方式（返回 Variant）
static func call_method(obj: Object, method: StringName, args: Array = []) -> Variant:
	if obj == null or not obj.has_method(method):
		push_error("GSInterface: 对象 %s 未实现方法 %s" % [obj.get_class() if obj else "<null>", method])
		return null
	return obj.callv(method, args)


## 视图解包：仅当对象同时具有 _target 与 _forward（即接口视图包装壳）时解包，
## 避免误伤自身带有 _target 成员的普通对象（如相机）。
static func _unwrap(obj: Object) -> Object:
	var hops := 0
	while obj != null and hops < 8 and "_target" in obj and obj.has_method(&"_forward"):
		var t: Object = obj.get("_target")
		if t == null:
			break
		obj = t
		hops += 1
	return obj


## 名义检查：obj 的脚本继承链是否包含 target（等价于 obj is target）
static func _is_subclass_of_script(obj: Object, target: Script) -> bool:
	var s: Script = obj.get_script()
	while s != null:
		if s == target:
			return true
		s = s.get_base_script()
	return false


## 收集契约方法：沿父类链收集接口声明的实例方法（跳过静态、_ 前缀、@ 属性访问器）
static func collect_methods(script: Script) -> Array[StringName]:
	var out: Array[StringName] = []
	var s: Script = script
	while s != null:
		for m in s.get_script_method_list():
			var name := StringName(m.get("name", ""))
			var flags := int(m.get("flags", 0))
			if flags & METHOD_FLAG_STATIC:
				continue
			if name.begins_with("_") or name.begins_with("@"):
				continue
			if not out.has(name):
				out.append(name)
		s = s.get_base_script()
	return out


## 收集契约属性：通过探针实例收集脚本声明的成员属性（含继承链）
static func collect_properties(script: Script) -> Array[StringName]:
	var out: Array[StringName] = []
	var probe: Variant = script.new()
	if probe == null or not (probe is Object):
		return out
	for p in (probe as Object).get_property_list():
		var usage := int(p.get("usage", 0))
		if not (usage & PROPERTY_USAGE_SCRIPT_VARIABLE):
			continue
		var name := StringName(p.get("name", ""))
		if name.begins_with("_"):
			continue
		if not out.has(name):
			out.append(name)
	return out


## 全局脚本类名 -> 路径（依赖引擎运行时暴露全局类列表；不可用时返回空串）
static func find_global_class_path(cn: StringName) -> String:
	for entry in get_global_class_list():
		if StringName(entry.get("class", "")) == cn:
			return str(entry.get("path", ""))
	return ""


static func get_global_class_list() -> Array:
	return ProjectSettings.get_setting("_global_script_classes", [])
