extends Node

var QuoteLeft = "`"
var Minus = "-"
var Equal = "="
var BracketLeft = "["
var BracketRight = "]"
var BackSlash = "\\"
var Semicolon = ";"
var Apostrophe = "\'"
var Comma = ","
var Period = "."
var Slash = "/"

var Up = "^"
var Down = "_"
var Left = "<"
var Right = ">"
var Space = ":"
var Alt = "a"
var Backspace = "b"
var Ctrl = "c"
var Delete = "d"
var Enter = "e"
var Home = "h"
var Insert = "i"
var CapsLock = "l"
var Menu = "m"
var NumLock = "n"
var Shift = "s"
var Tab = "t"
var Windows = "w"
var End = "z"
var PageUp = "{"
var PageDown = "}"
var Escape = "~"

func get_key_from_name(key_name:String):
	return get(key_name)
